spring:
  application:
    name: ConfigServer

  cloud:
     config:
       server:
         git:
           uri: https://github.com/dibyajyotipanigrahi/HealthConfig.git
           clone-on-start: true

server:
  port: 2222